version: "3"

services:
  # next:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports: [ "3000:3000" ]
  #   volumes:
  #     - /app/node_modules
  #     - .:/app

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports: [ "8090:8090" ]
    volumes: 
      - pb_data:/pb_data
      - ./src/backend/types.d.ts:/pb_data/types.d.ts
      - ./src/backend/migrations:/pb_migrations
      - ./src/backend/hooks:/pb_hooks

volumes: 
  pb_data:
