version: "3"

services:

  # ┏━ NextJS | A framework to build web apps.
  next:
    image: node:20-alpine
    command: >
      sh -c 'npm ci && if [ "$PRODUCTION" == "true" ]; 
        then npm run build && npm start
        else npm run dev
      fi'
    restart: unless-stopped
    working_dir: /app
    depends_on: [ pocketbase ]
    volumes:
      - next_build:/app/.next
      - ./node_modules:/app/node_modules
      - ./:/app

  # ┏━ Pocketbase | This'll provide our backend.
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.20
    restart: unless-stopped
    volumes:
      - pocketbase_data:/pb_data
      - ./src/backend/types.d.ts:/pb_data/types.d.ts
      - ./src/backend/migrations:/pb_migrations
      - ./src/backend/hooks:/pb_hooks

  # ┏━ Nginx | Ensures same origin for both services.
  nginx:
    image: nginx:1.25
    depends_on: [ next, pocketbase ]
    volumes: [ "./src/backend/routes:/etc/nginx/conf.d" ]
    ports: [ "${PORT:-3000}:3000" ]
    attach: false

volumes:
  next_build:
  next_modules:
  pocketbase_data:
