version: "3"

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports: [ "8000:8090" ]
    volumes: 
      - ./src/migrations:/pb_migrations
      - ./src/types/pocketbase.d.ts:/pb_data/types.d.ts
      - pb_data:/pb_data

volumes: 
  pb_data:
