
# ----- Uncomment to enable this workflow -----
# on:
#   push:
#     branches: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@master
        with:
          key:      ${{ secrets.DEPLOY_KEY }} 
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port:     ${{ secrets.DEPLOY_PORT }}
          script: |
            mkdir /root /root/env /root/env/${{ github.event.repository.name }}
            cd ~/env/${{ github.event.repository.name }}

            git clone ${{github.repository}} .
            git pull

            echo ${{ secrets.DEPLOY_ENV }} > .env
            
            docker-compose down ; docker-compose up -d
