name: deploy

# ----- Rename "leaflet" to a valid branch -----
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # ----- Ensure all environment vars are configured -----
      #          DEPLOY_ (KEY, HOST, USER, PORT, ENV)
      - uses: appleboy/ssh-action@master
        with:
          key:      ${{ secrets.DEPLOY_KEY }} 
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port:     ${{ secrets.DEPLOY_PORT }}
          script: |
            mkdir ~/env ~/env/${{github.repository}}
            cd ~/env/${{github.repository}}

            sudo git clone https://github.com/${{github.repository}} .
            sudo git pull

            echo '${{ secrets.DEPLOY_ENV }}' > .env
            
            sudo docker-compose down
            sudo docker-compose up -d
