name: deploy

# ----- Rename "leaflet" to a valid branch -----
on:
  push:
    branches: leaflet

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # ----- Ensure all environment vars are configured -----
      #          DEPLOY_ (KEY, HOST, USER, PORT, ENV)
      # KEY: Private (passwordless) ssh key.
      # HOST: Public IP or Local (etc: 192.168.1.100).
      # PORT: Usually 22 for SSH.
      # ENV: A copy of sample.env.
      - uses: appleboy/ssh-action@master
        with:
          key:      ${{ secrets.DEPLOY_KEY }} 
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port:     ${{ secrets.DEPLOY_PORT }}
          script: |
            mkdir ~/env ~/env/${{ github.event.repository.name }}
            cd ~/env/${{ github.event.repository.name }}

            git clone https://github.com/${{github.repository}} .
            git pull

            echo '${{ secrets.DEPLOY_ENV }}' > .env
            
            docker-compose down ; docker-compose up -d
