
# ----- Uncomment to enable this workflow -----
# on:
#   pull_request:
#     branches: main

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Obtain Repository
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm i

      - name: Validate Integrity
        run: npm run lint
