
# To run the server in development comment
#   out the "app" service in its entirety.

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
  server:
    image: directus/directus
    restart: unless-stopped
    environment:
      PUBLIC_URL: "http://localhost:3000"

      KEY: "255d861b-b5b5-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-5ea1-c8022c45e263"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"

      CORS_ENABLED: true
      CORS_ORIGIN: "http://localhost:3000"
    volumes:
      - ./server/uploads:/directus/uploads
      - ./server/extensions:/directus/extensions
      - ./server/database:/directus/database
    ports:
      - 8055:8055
