version: "3"
services:

  # v -- NextJS | Frontend, react based compiled webapp.
  app:
    ports: [3000:3000]

    image: node:lts-alpine
    restart: unless-stopped
    working_dir: /usr/app
    env_file: .env
    volumes: [.:/usr/app]
    command: ["yarn", "ci"]
    profiles: ["prod"]

  # v -- Directus | Backend CMS solution, accessible via API.
  server:
    ports: [8055:8055]

    image: directus/directus:latest
    restart: unless-stopped
    networks: [server]
    env_file: .env
    environment:
      CORS_ENABLED: "true"
      PUBLIC_URL: $CORS_ORIGIN
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: $SECRET
    volumes:
      - ./source/shared/uploads:/directus/uploads
      - ./source/extensions:/directus/extensions

  # v -- Postgres | Data storage as required by Directus.
  database:
    image: postgis/postgis:latest
    restart: unless-stopped
    depends_on: [server]
    networks: [server]
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $SECRET
    volumes: [./source/shared/database:/var/lib/postgresql/data]

networks:
  server: